version: "3.9"
services:
  preprocessing:
    build: .
    image: pro-train
    volumes:
      - ~/.aws/:/root/.aws:ro
    command: preprocessing-script.py
  training:
    depends_on:
      preprocessing:
        condition: service_completed_successfully
    image: pro-train
    volumes:
      - ~/.aws/:/root/.aws:ro
    command: training-script.py
