name: protrain-sagemaker

on:
  workflow_dispatch
  
env:
  APPLICATION_NAME: startupapp

jobs:
  build_image_push_to_ECR:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # see: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    
    - run: |
        sudo apt-get update
        chmod 755 training-script.py
        chmod 755 sudo-dependency.sh
        
        ./sudo-dependency.sh
        python3 training-script.py
        #cat details.txt >> report.md
        #cml-send-comment report.md 
